dataset:
  pred_root: C:/Users/ciroc/Desktop/AV_project/data/models/evaluation/soccana_1cls_640_smoothed_v2
  gt_root:   C:/Users/ciroc/Desktop/AV_project/data/datasets/SoccerNet/tracking/test1

video:
  width: 1920
  height: 1080

roi:
  json: C:/Users/ciroc/Desktop/AV_project/data/rois/roi.json

patterns:
  pred_tracking: "C:/Users/ciroc/Desktop/AV_project/data/models/evaluation/soccana_1cls_640_smoothed_v2/tracking_*.txt"
  gt_tracking: "C:/Users/ciroc/Desktop/AV_project/data/datasets/SoccerNet/tracking/test1/*/gt/gt.txt"
output:
  pred_behavior_dir: C:/Users/ciroc/Desktop/AV_project/data/models/evaluation/soccana_1cls_640_smoothed_v2

naming:
  team_id: 1   


paths:
  dataset_root: "C:/Users/ciroc/Desktop/AV_project/data/datasets/SoccerNet"
  roi_json_path: "C:/Users/ciroc/Desktop/AV_project/data/rois/roi.json"