
seq_root: C:/Users/ciroc/Desktop/AV_project/data/datasets/SoccerNet/tracking/test

out_name: SoccerNet_Crops_for_ReID
img_subdir: img1
gt_relpath: gt/gt.txt
dataset_mode: test

min_conf: 1.0
min_box_area: 400
query_per_id: 1
gallery_per_id: 1
seed: 17
max_per_id: 0
